services:

  nginx:
    build:
      context: requirements/nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - ./home/tbraud/data/wordpress_data:/var/www/html
      - ./home/tbraud/data/nginx_data/cert:/etc/nginx/certs/
    ports:
      - "443:443"
    networks:
      - frontend
      - backend

  wordpress:
    build:
      context: requirements/wordpress
    hostname: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ROOT_USER: ${WP_ROOT_USER}
      WP_ROOT_PASSWORD: ${WP_ROOT_PASSWORD}
      WP_ROOT_EMAIL: ${WP_ROOT_EMAIL}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./home/tbraud/data/wordpress_data:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - backend

  mariadb:
    build:
      context: requirements/mariadb
    hostname: ${MYSQL_DB_HOST}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--silent"]
      interval: 0.1s
      timeout: 2s
      retries: 10
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./home/tbraud/data/mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

volumes:
  wordpress_data:
  mariadb_data:
  nginx_data:

networks:
  frontend:
      driver: bridge
  backend:
      driver: bridge
